export const PATHS = {
  LANDING: "/",
  HOME: "/home",
  PENDING_INVITATIONS: "/pending-invitations",
  JOINED_ROOMS: "/joined-rooms",
  PROFILE: "/profile",
  OWN_ROOMS: "/my-own-rooms",
  CERTIFICATES: "/certificates",
  LEARNING_PATH: "learning-path",
  COURSES: "courses",
  COURSE_PLAYER: "course-player/:courseId",
  LESSON: "lesson/:lessonId",
  QUIZ: "quiz/:sectionId",
  CHAT_GROUPS: "chats",
  WEEKLY_TASKS: "weekly-tasks",
  LEADERBOARD: "leaderboard",
  GROUP_WORKSPACE: "group-workspace",
  DEPARTMENTS: "departments",

  SIGNIN: "/signin",

  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  SIGNUP: "/signup",
  DEMO: "/demos/:demoId",
  CHECK_EMAIL: "/check-email",
  VERIFY_EMAIL: "/verify-email",
  VERIFIED_SUCCESSFULLY: "/verified-successfully",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  PAYMENT_SUCCESS: "/payment-success",
  REQUEST_ROOM: "/request-room",
  MEMBERS: "members",
  TOOLS: "tools",
  DEMO_SECTION: "/demos/:demoId/departments/:departmentId",

  INQUIRIES: "inquiries",

  OWNER_HOME: "analytics-home",
  OWNER_MEMBERS: "members",
  OWNER_LIBRARY: "library",
  OWNER_COURSES: "manage-courses",
  PSD_COURSES: "Purchased-courses",

  SM_ASSETS: "demo-assets",
  SM_MEMBERS: "members",
  SM_TOOLS: "tools",
  SM_LEARNING_PATH: "learning-path",
  ROADMAPS: "roadmaps",
  // SM_ROADMAPS: "roadmaps",
  SM_TASKS: "weekly-tasks",
  LIVES: "lives",
  LIVE_ROOM: "/demos/:demoId/departments/:departmentId/lives/:streamId/room",

  COURSE_STUDIO: "course-studio",
  MANAGE_COURSE: "manage-course/:assetId",
};
