export const PATHS = {
  HOME: "/",
  PENDING_INVITATIONS: "/pending-invitations",
  JOINED_ROOMS: "/joined-rooms",
  PROFILE: "/profile",
  OWN_ROOMS: "/my-own-rooms",
  LEARNING_PATH: "/learning-path",
  COURSES: "/courses",
  ROAD_MAP: "/road-map",
  WEEKLY_TASKS: "/weekly-tasks",
  LEADERBOARD: "/leaderboard",
  GROUP_WORKSPACE: "/group-workspace",
  GROUP_CHAT: "/group-chat",
  DEPARTMENTS: "/departments",
  CERTIFICATES: "/certificates",
  LIVES: "/lives",
  CHAT_CHANNEL: "/chat-channel",
  INQUIRIES: "/inquiries",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
};
