export const PATHS = {
  LANDING: "/",
  HOME: "/home",
  PENDING_INVITATIONS: "/pending-invitations",
  JOINED_ROOMS: "/joined-rooms",
  PROFILE: "/profile",
  OWN_ROOMS: "/my-own-rooms",
  LEARNING_PATH: "learning-path",
  COURSES: "courses",
  ROAD_MAP: "road-map",
  WEEKLY_TASKS: "weekly-tasks",
  LEADERBOARD: "leaderboard",
  GROUP_WORKSPACE: "group-workspace",
  GROUP_CHAT: "/group-chat",
  DEPARTMENTS: "/departments",
  CERTIFICATES: "/certificates",

  SIGNIN: "/signin",
  CHAT_CHANNEL: "chat-channel",
  INQUIRIES: "/inquiries",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  SIGNUP: "/signup",
  DEMO: "/demos/:demoId",
  CHECK_EMAIL: "/check-email",
  VERIFY_EMAIL: "/verify-email",
  VERIFIED_SUCCESSFULLY: "/verified-successfully",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  REQUEST_ROOM: "/request-room",
  MEMBERS: "members",
  TOOLS: "tools",
  DEMO_SECTION: "/demos/:demoId/departments/:departmentId",

  OWNER_HOME: "analytics-home",
  OWNER_DEPTS: "departments",
  OWNER_MEMBERS: "members",
  OWNER_INQUIRIES: "inquiries",
  OWNER_LIBRARY: "library",

  SM_ASSETS: "demo-assets",
  SM_MEMBERS: "members",
  SM_COURSES: "courses",
  SM_INQUIRIES: "inquiries",
  SM_TOOLS: "tools",
  SM_LEARNING_PATH: "learning-path",
  SM_ROADMAPS: "roadmaps",
  SM_TASKS: "weekly-tasks",
  LIVES: "lives",
};
